version: 2
jobs:
  build:
    docker:
      - image: brandonwillard/org-publish:latest

    working_directory: ~/org-file-project-repo

    steps:

      - checkout

      - restore_cache:
         key: conda-{{ checksum "environment.yml" }}

      - run: conda update -qy -n base conda

      # A utility for adding new GitHub releases
      - run: |
          conda install -qy -c conda-forge go==1.10
          go get github.com/tcnksm/ghr

      # Our project/repo has a conda env specified in an 'environment.yml' file
      - run: conda env create --force -q -f environment.yml -n build-env

      - save_cache:
         key: conda-{{ checksum "environment.yml" }}
         paths:
           - "/opt/conda"

      # Activate our conda env and compile our Org file to PDF.
      - run: |
          . /opt/conda/etc/profile.d/conda.sh
          conda activate build-env
          make -C src/org -f Makefile the-resulting.pdf

      # Save the resulting PDF and any images produced.
      - store_artifacts:
          path: ~/org-file-project-repo/output/the-resulting.pdf
      - store_artifacts:
          path: ~/org-file-project-repo/figures

      # Create the GitHub release (needs a tag from `git describe --tags`).
      # XXX: You'll need to create a GitHub API token environment variable
      # (named 'GITHUB_TOKEN') in the CircleCI project.
      - deploy:
          command: /root/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -replace -prerelease `git describe --tags` output/the-resulting.pdf

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
